"""empty message

Revision ID: a2a479cf84df
Revises: 6bafd4963cd1
Create Date: 2022-06-01 10:18:20.035851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2a479cf84df'
down_revision = '6bafd4963cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'joi_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joi_time', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'join_time')
    # ### end Alembic commands ###
